### ISSUE TITLE
don't force user to use the same name as the IDE launcher

### ISSUE THREAD

**Issue by jochenmusic** [nathan818fr/jetbrains-launcher#1]
interesting project, but it's annoying that you seem to force the user to use the same name as the IDE launcher.

e.g. allow a novel name like pycharm_proj.
I overrode this in the script.

**Comment by nathan818fr** [comment]
The easiest solution without modifying the script would be to define an alias in your shell config, using the undocumented variable `JETBRAINS_LAUNCHER_IDE_OVERRIDE`.
```
alias pycharm_proj='JETBRAINS_LAUNCHER_IDE_OVERRIDE=pycharm /path/to/jetbrains-launcher.sh'
```

---

I'm considering:
1. Documenting this use case, also explaining it in the README.
2. Be less strict on the script name check, allowing only partial matching (e.g. if it contains "pycharm" it's OK)

**Comment by nathan818fr** [comment]
I think we're good now with c31dbad78e7b2b586ea4b86e42efbfd1bb08e4c0 and 6ad4bb6c131f5c612877e7b3a7e1ccffa1a13ac4.
You can check the README again, it should meet your needs better.

Feel free to re-open this issue if necessary.

**Comment by jochenmusic** [comment]
Cool, I like the partial match solution.
