### ISSUE TITLE
Saves to wrong path?

### ISSUE THREAD

**Issue by jochenmusic** [nathan818fr/jetbrains-launcher#2]
Project is saved in JETBRAINS_PROJECTS_DIR but relative to the JETBRAINS_APPS_DIR. :(

export JETBRAINS_APPS_DIR=/Applications
export JETBRAINS_PROJECTS_DIR=/Users/jochen/pycharm_project_files

it creates /Applications/pycharm/Users/jochen/git/...../.idea

under macos

**Comment by nathan818fr** [comment]
Thanks for reporting.
I was using the wrong variables (`JETBRAINS_APPS_DIR` instead of `JETBRAINS_PROJECTS_DIR`).
It's fixed now.

**Comment by jochenmusic** [comment]
✌️ thanks for the quick fix.

**Comment by jochenmusic** [comment]
The fix didn't work :(

> ~   > echo $JETBRAINS_APPS_DIR     
> /Applications
> ~   > echo $JETBRAINS_PROJECTS_DIR
> /Users/jochen/pycharm_project_files
> ~   > pycharm_proj newproject
> Project directory: /Users/jochen/newproject
> Configuration directory: /Applications/pycharm/Users/jochen/pycharm/Users/jochen/newproject
> 

Looks like jetbrains_projects_dir gets overwritten? also, why have the ide_id in there?
 conf_dir="${jetbrains_projects_dir}/${ide_id}/$(appendable_path "$project_dir")"

**Comment by nathan818fr** [comment]
I really don't understand how the path can end like this in your case. 😕
Working for me on Linux and Windows:
```
$ export JETBRAINS_PROJECTS_DIR=/tmp/jetbrains-test
$ idea ~/repo/nathan818fr/jetbrains-launcher
Project directory: /home/user/repo/nathan818fr/jetbrains-launcher
Configuration directory: /tmp/jetbrains-test/idea/home/user/repo/nathan818fr/jetbrains-launcher
Initializing configuration
Starting IntelliJ IDEA (detached, use --no-detach to run in foreground)
```

I'm going to test it on macOS.

---

For the path, the `ide_id` is added to support multiple IDEs on the same project.
Otherwise, scripts from each IDE (which use the same `JETBRAINS_PROJECTS_DIR`) would end up using the same configuration directory.

**Comment by nathan818fr** [comment]
It also works on macOS for me:
```
$ export JETBRAINS_PROJECTS_DIR=/Users/user/JetBrainsProjects
$ pycharm ~/Documents/test-project
Project directory: /Users/user/Documents/test-project
Configuration directory: /Users/user/JetBrainsProjects/pycharm/Users/user/Documents/test-project
Initializing configuration
Starting PyCharm (detached, use --no-detach to run in foreground)
```

~~@jochenmusic can you provide me the output of the following commands please:~~ (edit: see next comment)
```
pycharm_proj --version
declare -p JETBRAINS_APPS_DIR
declare -p JETBRAINS_PROJECTS_DIR
```

**Comment by nathan818fr** [comment]
@jochenmusic I added a `--debug-report` option to better handle such issues (229c0ecac9d081cdd9c5d77095db4c456650606f).

Please update, run `pycharm_proj --debug-report` and paste the full output here (and if this fails, paste the output of `pycharm_proj --version`).

**Comment by jochenmusic** [comment]
~   > pycharm_proj --version 
JetBrains Launcher version: 2023-12-11.2 (https://github.com/nathan818fr/jetbrains-launcher)
JetBrains Launcher platform: mac
~   > pycharm_proj --debug-report
$VERSION=2023-12-11.2
$JETBRAINS_APPS_DIR=/Applications
$JETBRAINS_PROJECTS_DIR=/Users/jochen/pycharm_project_files
$JETBRAINS_LAUNCHER_IDE_OVERRIDE=''
$JETBRAINS_PYCHARM_COMMAND=/usr/local/bin/pycharm
$launcher_platform=mac
$jetbrains_apps_dir=/Applications
$jetbrains_projects_dir=/Applications/pycharm/Users/jochen
$ide_id=pycharm
pwd()=/Users/jochen
read_path(Hello123)=/Users/jochen/Hello123
write_path(Hello123)=Hello123
appendable_path(Hello123)=Hello123
read_path(Hello123/World)=/Users/jochen/Hello123/World
write_path(Hello123/World)=Hello123/World
appendable_path(Hello123/World)=Hello123/World
read_path(Hello123\\World)=/Users/jochen/Hello123\\World
write_path(Hello123\\World)=Hello123\\World
appendable_path(Hello123\\World)=Hello123\\World
read_path(/Foo123)=/Foo123
write_path(/Foo123)=/Foo123
appendable_path(/Foo123)=Foo123
read_path(C:\\Foo123)=/Users/jochen/C:\\Foo123
write_path(C:\\Foo123)=C:\\Foo123
appendable_path(C:\\Foo123)=C:\\Foo123
read_path(C:/Foo123)=/Users/jochen/C:/Foo123
write_path(C:/Foo123)=C:/Foo123
appendable_path(C:/Foo123)=C:/Foo123
find_ide_command()=/usr/local/bin/pycharm

**Comment by jochenmusic** [comment]
I think it's a version problem with `realpath`. I haven't debugged it, but fixed the script directly (see commented-out line).

```
   if [[ -n "${JETBRAINS_PROJECTS_DIR:-}" ]]; then
     printf '### $JETBRAINS_PROJECTS_DIR=%q\n' "${JETBRAINS_PROJECTS_DIR:-}"
     path=$(read_path "$JETBRAINS_PROJECTS_DIR")
     # path=$JETBRAINS_PROJECTS_DIR
     declare -gr jetbrains_projects_dir=$path
     printf '### $jetbrains_projects_dir=%q\n' "${jetbrains_projects_dir:-}"
   else
 ```

```
 ~   > pycharm_proj --debug-report
 ### $JETBRAINS_PROJECTS_DIR=/Users/jochen/pycharm_project_files
 ### $jetbrains_projects_dir=/Applications/pycharm/Users/jochen
```

**Comment by nathan818fr** [comment]
Yes, it seems related to realpath.
What is the output of `ls -ld /Users/jochen/pycharm_project_files` ?

**Comment by nathan818fr** [comment]
@jochenmusic Ok, so I improved paths normalization (24e26d5978c80916869e661bdef7c491823dc29a):
- stop resolving symbolic links
- make sure GNU realpath provided by coreutils is used on macOS (`grealpath` instead of `realpath`)

I hope this will solve your problem.
You should obtain this "Configuration directory":
`/Users/jochen/pycharm_project_files/pycharm/Users/jochen/newproject`

Edit: This path may seem a little long/complex.
But I need to add the `ide_id` to ensure compatibility when opening the same project with different JetBrains IDEs.
And add the full project path to ensure there are no collisions between different projects with the same name.

**Comment by jochenmusic** [comment]
Great, the switch to grealpath fixed it. Thanks! :)

**Comment by nathan818fr** [comment]
Great, thanks for your patience and help!
