### ISSUE TITLE
fix didn't work

### ISSUE THREAD

**Issue by jochenmusic** [nathan818fr/jetbrains-launcher#3]
(hiya, I couldn't reopen the issue, so just filing a new one ;)

The fix didn't work :(

~ > echo $JETBRAINS_APPS_DIR
/Applications
~ > echo $JETBRAINS_PROJECTS_DIR
/Users/jochen/pycharm_project_files
~ > pycharm_proj newproject
Project directory: /Users/jochen/newproject
Configuration directory: /Applications/pycharm/Users/jochen/pycharm/Users/jochen/newproject

Looks like jetbrains_projects_dir gets overwritten? also, why have the ide_id in there?
conf_dir="${jetbrains_projects_dir}/${ide_id}/$(appendable_path "$project_dir")"

**Comment by nathan818fr** [comment]
Reopened
